stasson/vue-mdc-adapter

- src/components/Drawer/mdc-temporary-drawer.vue
got the drawer anyway, still working on that toolbar
> add temporary drawer

- build/dev-server.js
- components/checkbox/mdc-checkbox.vue
- components/layout-grid/mdc-layout-grid.vue
- components/radio/mdc-radio.vue
- components/switch/mdc-switch.vue
- package.json
- use http instead of https
- fix lint error (no multiple blank lines)
- add missing dev dependencies
> fix dev build

- components/drawer/index.js
- components/drawer/mdc-drawer-header.vue
- components/drawer/mdc-drawer-toolbar-spacer.vue
- components/drawer/mdc-permanent-drawer.vue
- components/drawer/mdc-persistent-drawer.vue
- components/drawer/mdc-temporary-drawer.vue
- src/docs/Doc.vue
> implement all drawer components

- src/components/drawer/mdc-drawer-toolbar-spacer.vue
docs: https://material.io/components/web/catalog/drawers/
> fix a class name bug of drawer  

- components/dialog/mdc-dialog.scss
- components/fab/mdc-fab.scss
- components/fab/mdc-fab.vue
- components/menu/mdc-menu.scss
- components/menu/mdc-menu.vue
- components/snackbar/mdc-snackbar.scss
> z-index temporary fixes

- package.json
> use babel-cli instead of babel

- components/drawer/mdc-drawer-item.vue
- components/styles.scss
drawer items in demo will now trigger the `pointer` cursor mode
closes #124
> fix(drawer): make drawer items use the pointer cursor

- components/checkbox/mdc-checkbox.vue
do register on ripple interaction listeners on wrapper vs root and label
fixes #135
> fix(checkbox): checkbox throws error if no label #135

- CONTRIBUTING.md
> feat(docs): add style guide

- components/drawer/README.md
- components/drawer/mdc-drawer.vue
- components/drawer/test.spec.js
> feat(drawer): add drawer-type prop for easy drawer type switching

- components/textfield/README.md
- components/textfield/mdc-textfield.vue
> feat(textfield): emit blur event from input or textarea element

- components/list/README.md
- Fix `avatar-list` props in examples
- Fix `span` end tag in examples
> docs(list): fix list examples

- components/drawer/mdc-drawer.vue
> fix(drawer): make responsive behaviour consistent

- components/base/auto-init.js
- components/base/base-plugin.js
- components/index.js
- package-lock.json
- package.json
- rollup.config.js
> feat: distribution should have a version #129

- components/select/mdc-menu-select.vue
> fix(select): select with pre-selected option doesn't float label #188

- components/checkbox/README.md
- components/checkbox/mdc-checkbox.vue
- components/radio/README.md
- components/radio/mdc-radio.vue
- components/switch/README.md
- components/switch/mdc-switch.vue
- components/unit-test/index.js
also refactor using formfield foundation
closes #185
> feat(checkbox): allow custom label markup

- components/textfield/README.md
- components/textfield/demo.vue
- components/textfield/mdc-textfield.vue
Hello,
Some additions to the text-field component to implement text-field--box feature described in the official material documentation: https://material.io/components/web/catalog/input-controls/text-fields/
Paul
> feat(text-field): add text-field--box support

- components/textfield/README.md
- components/textfield/mdc-textfield.vue
- components/unit-test/polyfills.js
also add custom validation property
closes #210
> fix(textfield): add missing type attribute

- components/select/package-lock.json
- components/unit-test/index.js
- package-lock.json
- package.json
> chore(package): update vue-test-utils to @vue/test-utils

- components/checkbox/README.md
- components/checkbox/mdc-checkbox.vue
- components/select/README.md
- components/select/mdc-option.vue
- components/select/mdc-select.vue
- components/switch/README.md
- components/switch/mdc-switch.vue
- components/textfield/README.md
- components/textfield/mdc-textfield.vue
> feat: add name property to texfield, checkbox, select, switch

- components/select/mdc-multi-option.vue
- components/select/mdc-native-option.vue
- components/snackbar/mdc-snackbar.vue
This fixes some props on select options and snackbar.
> fix: Component properties

- components/textfield/mdc-textfield.vue
> fix(textfield): textarea model value ignored

- components/select/mdc-menu-select.vue
> mdc-select: set menu styles directly

- components/list/README.md
- components/list/demo.vue
- components/list/mdc-list-item.vue
- components/list/mdc-list.vue
- components/select/styles.scss
- components/textfield/mdc-textfield.vue
- package-lock.json
- package.json
> mdc 0.29.0

- components/checkbox/mdc-checkbox.vue
- components/drawer/README.md
- components/drawer/mdc-drawer-item.vue
- components/menu/mdc-menu.vue
- components/menu/styles.scss
- components/radio/README.md
- components/radio/mdc-radio.vue
- components/ripple/mdc-ripple-base.js
- components/select/styles.scss
- components/textfield/README.md
- components/textfield/mdc-textfield.vue
- demo/styles/demo.scss
- package-lock.json
- package.json
closes #248 
closes #245 
closes #252
> MDCWeb 0.30.0

- .prettierrc.yaml
- components/chips/README.md
- components/chips/demo.vue
- components/chips/mdc-chip-set.vue
- components/chips/mdc-chip.vue
- components/chips/styles.scss
- components/index.js
- components/select/mdc-menu-select.vue
- components/styles.scss
- components/textfield/demo.vue
- components/textfield/mdc-textfield.vue
- components/top-app-bar/README.md
- components/top-app-bar/demo.vue
- components/top-app-bar/entry.js
- components/top-app-bar/index.js
- components/top-app-bar/mdc-top-app-bar--action.vue
- components/top-app-bar/mdc-top-app-bar.vue
- components/top-app-bar/styles.scss
- components/top-app-bar/test.spec.js
- demo/component.vue
- demo/links.js
- package-lock.json
- package.json
feat(mdc-top-app-bar): Implement `mdc-top-app-bar` as per MDC 0.32.0.
> pgbross-feat/mdc-top-app-bar

- components/slider/mdc-slider.vue
Fix(mdc-slider): Take into account current max value when initializing the min and max values.
Resolves #311
> fix(mdc-slider): Set min and max taking into account current max value.

- components/select/mdc-option.vue
- components/select/mdc-select.vue
> fix(mdc-select): Add menu prop

- components/chips/demo.vue
- components/chips/mdc-chip-set.vue
- components/chips/mdc-chip.vue
Implement checkmark added in material-components-web@0.33.0 for filter chips
> feat(mdc-chips): Implement checkmark for filter chips

- components/menu/README.md
- components/menu/mdc-menu.vue
- package.json
Add support for menu quick-open.
Resolves #261
> feat(mdc-menu): Add support for quick-open.

- components/menu/README.md
- components/menu/mdc-menu.vue
feat(mdc-menu): Add new anchor postioning functionality.
Resolves #202
> feat(mdc-menu): Add new anchor postioning functionality.

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 0.13.2

- .github/ISSUE_TEMPLATE.md
> docs: add issue template

- components/textfield/mdc-textfield.vue
Pass attributes from parent scope onto input elements.
Resolves #331
> fix(mdc-textfield): Bind scope attributes to input elements.

- components/tabs/demo.vue
- components/tabs/mdc-tab.vue
Fix hasIcon() computed to return result.
> fix(mdc-tab): show icons in tabs

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 0.13.3

- CHANGELOG.md
- package.json
fix duplicate isssues in changelog
> docs: fix changelog

- CHANGELOG.md
- package-lock.json
- package.json
> chore: v0.13.5

- components/textfield/mdc-textfield.vue
Support number as permitted type attribute value.
Resolves #346
> fix(mdc-textfield): Support number as permitted type attribute value.

- components/drawer/mdc-drawer.vue
- components/slider/mdc-slider.vue
- components/snackbar/mdc-snackbar.vue
> fix: Remove event listeners on component destroy

- components/base/dispatch-event-mixin.js
- components/button/mdc-button-base.vue
- components/card/mdc-card-action-icon.vue
- components/card/mdc-card-primary-action.vue
- components/common/event-bus.js
- components/drawer/mdc-drawer-item.vue
- components/drawer/mdc-drawer.vue
- components/fab/mdc-fab.vue
- components/grid-list/mdc-grid-list.vue
- components/grid-list/mdc-grid-tile.vue
- components/tabs/mdc-tab-bar.vue
- components/tabs/mdc-tab.vue
- components/toolbar/mdc-toolbar-icon.vue
- components/toolbar/mdc-toolbar-menu-icon.vue
- components/toolbar/mdc-toolbar-title.vue
- components/top-app-bar/mdc-top-app-bar--action.vue
- components/top-app-bar/mdc-top-app-bar.vue
- package-lock.json
Refactor dispatch event mixin to support underlying html and  material-components-web events as well as global event bus
> feat: dispatchevent

- components/snackbar/mdc-snackbar.vue
> fix(mdc-snackbar): typo in removing event source listener

- components/checkbox/mdc-checkbox.vue
- components/common/unique-id.js
- components/dialog/mdc-dialog.vue
- components/radio/mdc-radio.vue
- components/switch/mdc-switch.vue
- components/textfield/mdc-textfield.vue
> fix(mdc-dialog): use vue-mdc-adapter unique id

- components/layout-grid/demo.vue
- components/layout-grid/mdc-layout-grid.vue
> feat(mdc-layout-grid): add support for overall grid layout alignment

- components/tabs/mdc-tab-bar.vue
> fix(mdc-tab-bar): Guard against deactivating a tab that no longer exists

- components/checkbox/mdc-checkbox.vue
> feat(mdc-checkbox): Support array as v-model.

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 0.14.0

- components/snackbar/README.md
- components/snackbar/demo.vue
- components/snackbar/mdc-snackbar.vue
> feat(mdc-snackbar): Support v-model to show snack.

- components/dialog/README.md
- components/dialog/demo.vue
- components/dialog/mdc-dialog.vue
> feat(mdc-dialog): Support v-model for open/close dialog

- components/menu/README.md
- components/menu/demo.vue
- components/menu/mdc-menu.vue
> feat(mdc-menu): Support v-model for open/close

- components/top-app-bar/README.md
- components/top-app-bar/demo.vue
- components/top-app-bar/mdc-top-app-bar.vue
> feat(mdc-top-app-bar): Add support for prominent prop

- package-lock.json
- package.json
> Greenkeeper/rollup 0.58.1

- components/checkbox/mdc-checkbox.vue
> fix(mdc-checkbox): Correct classname for svg path.

- components/base/index.js
- components/base/uniqueid-mixin.js
- components/checkbox/mdc-checkbox.vue
- components/dialog/mdc-dialog.vue
- components/radio/mdc-radio.vue
- components/switch/mdc-switch.vue
- components/textfield/mdc-textfield.vue
> Pgbross fix/unique id/mix

- docs/getting-started.md
> Added instruction to configure vue.config.js for scss path

- docs/getting-started.md
> Fixed css loaderOptions example in getting-started

- components/drawer/mdc-drawer-item.vue
replace closeDrawer() to close()
> replace closeDrawer() to close()

- components/radio/mdc-radio.vue
Resolves: https://github.com/stasson/vue-mdc-adapter/issues/475
> fix(mdc-radio): Add 'checked' watcher

- components/tabs/mdc-tab.vue
> bug(tabs): Watch tabs active state.

- components/menu/styles.scss
> fix(menu): menu styles should import list styles
